from __future__ import annotations

__all__: list[str] = [
    "throw_abort",
    "throw_access_violation",
    "throw_double_free",
    "throw_stack_overflow",
]

def throw_abort() -> None: ...
def throw_access_violation() -> None: ...
def throw_double_free() -> None: ...
def throw_stack_overflow() -> None: ...
